FROM python:3.12
WORKDIR /app

COPY requirements.txt api.py model.py .flaskenv ./
WORKDIR /app/models
COPY models ./
WORKDIR /app
RUN pip install -r requirements.txt
ENV FLASK_ENV production

EXPOSE 5001
CMD ["gunicorn", "-b", ":5001", "api:app"]